'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CarsInventory

    Partial Public Class Car
        Public Property Id As Integer
        Public Property Brand As String
        Public Property Model As String
        Public Property Year As Nullable(Of Integer)
        Public Property Price As Nullable(Of Decimal)
        Public Property IsNew As Nullable(Of Boolean)
        Public Property CreatedBy As Nullable(Of Integer)
    
    End Class

End Namespace
