'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace CarsInventory

    Partial Public Class CarsInventoryEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=CarsInventoryEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Cars() As DbSet(Of Car)
        Public Overridable Property Users() As DbSet(Of User)
    
    End Class

End Namespace
