'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CarsInventory

    Partial Public Class User
        Public Property Id As Integer
        Public Property Name As String
        Public Property Username As String
        Public Property Password As String
    
    End Class

End Namespace
